version: "3.9"

services:
  web:
    build:
      context: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Указываем путь к .env файлу
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6380:6379"
